"""remove unique contraint from paper

Revision ID: 0d77fb371ed2
Revises: 0cb2d2d78f74
Create Date: 2019-09-26 00:10:42.307563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d77fb371ed2'
down_revision = '0cb2d2d78f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_papers_doi', table_name='papers')
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.drop_index('ix_papers_title', table_name='papers')
    op.create_index(op.f('ix_papers_title'), 'papers', ['title'], unique=False)
    op.drop_index('ix_papers_url', table_name='papers')
    op.create_index(op.f('ix_papers_url'), 'papers', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_url'), table_name='papers')
    op.create_index('ix_papers_url', 'papers', ['url'], unique=1)
    op.drop_index(op.f('ix_papers_title'), table_name='papers')
    op.create_index('ix_papers_title', 'papers', ['title'], unique=1)
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.create_index('ix_papers_doi', 'papers', ['doi'], unique=1)
    # ### end Alembic commands ###
