"""Added papers

Revision ID: 3555eaf4f8a7
Revises: c9442d2b81af
Create Date: 2019-09-20 00:41:02.866426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3555eaf4f8a7'
down_revision = 'c9442d2b81af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('proposer_id', sa.Integer(), nullable=True))
    op.drop_index('ix_papers_proposer', table_name='papers')
    op.create_foreign_key(None, 'papers', 'users', ['proposer_id'], ['id'])
    op.drop_column('papers', 'proposer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('proposer', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.create_index('ix_papers_proposer', 'papers', ['proposer'], unique=False)
    op.drop_column('papers', 'proposer_id')
    # ### end Alembic commands ###
