"""empty message

Revision ID: c9442d2b81af
Revises: 2e65fec5724a
Create Date: 2019-09-20 00:00:39.239875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9442d2b81af'
down_revision = '2e65fec5724a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('proposer', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_index(op.f('ix_papers_proposer'), 'papers', ['proposer'], unique=False)
    op.create_index(op.f('ix_papers_title'), 'papers', ['title'], unique=True)
    op.create_index(op.f('ix_papers_url'), 'papers', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_url'), table_name='papers')
    op.drop_index(op.f('ix_papers_title'), table_name='papers')
    op.drop_index(op.f('ix_papers_proposer'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
